---
title: "Glyphosate concentration in honey samples"
author: "Erick Motta"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(cowplot)
```

# Figure 3F - SITE 1, 2018:
```{r Model}
honey_site1_2018 <- read.table("tables/honey-site1-2018.txt", header = T)

# Function to calculate the mean and the standard deviation for each group
# data: a data frame
# varname: the name of a column containing the variable to be summarized
# groupnames: vector of column names to be used as grouping variables
data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      sd = sd(x[[col]], na.rm=TRUE))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- rename(data_sum, c("mean" = varname))
 return(data_sum)
}

# Summarize the data:
hd1_2018 <- data_summary(honey_site1_2018, varname="Concentration", groupnames=c("Treatment", "Week"))

# Organize:
hd1_2018$Treatment <- factor(hd1_2018$Treatment, levels = c("Control","0_1RS"))

#Line plot with error bars:
hd1_2018_graph <- ggplot(hd1_2018, aes(x=Week, y=Concentration, group=Treatment, color=Treatment)) + 
  geom_line(size = 1, position = position_dodge(width = 0.2), alpha = 0.2, linetype = "dashed") +
  geom_point(size = 4, aes(shape = Treatment, fill = Treatment), position = position_dodge(width = 0.2)) +
  geom_errorbar(aes(ymin=Concentration-sd, ymax=Concentration+sd), size = 1, width = 0, position = position_dodge(width = 0.2)) +
  scale_y_continuous(breaks = c(0,300,600,900,1200,1500)) +
  scale_x_continuous(breaks = c(0,1,2,3,4,5,6,7)) +
  scale_shape_manual(values = c(16,17)) +
  scale_color_manual(values=c('#999999','#E69F00'))+
  theme_classic() +
  ggtitle("Site 1 - 2018") +
  theme(plot.title = element_text(face = "plain", size = 10, hjust = 0.5)) +
  theme(axis.text.x = element_text(color = "black", size = 10),
        axis.text.y = element_text(color = "black", size = 10)) +
  theme(axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10)) +
  ylab(bquote("Glyphosate concentration ("*mu~"g/mL)")) +
  theme(legend.position = "none")
```

# Figure 4D - SITE 1, 2019:
```{r Model}
honey_site1_2019 <- read.table("tables/honey-site1-2019.txt", header = T)

# Function to calculate the mean and the standard deviation for each group
# data: a data frame
# varname: the name of a column containing the variable to be summarized
# groupnames: vector of column names to be used as grouping variables
data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      sd = sd(x[[col]], na.rm=TRUE))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- rename(data_sum, c("mean" = varname))
 return(data_sum)
}

# Summarize the data:
hd1_2019 <- data_summary(honey_site1_2019, varname="Concentration", groupnames=c("Treatment", "Week"))

# Organize:
hd1_2019$Treatment <- factor(hd1_2019$Treatment, levels = c("Control","0_001RS","0_1RS","0_001R","0_1R"))

#Line plot with error bars:
hd1_2019_graph <- ggplot(hd1_2019, aes(x=Week, y=Concentration, group=Treatment, color=Treatment)) + 
  geom_line(size = 1, position = position_dodge(width = 0.6), alpha = 0.2, linetype = "dashed") +
  geom_point(size = 4, aes(shape = Treatment, fill = Treatment), position = position_dodge(width = 0.6)) +
  geom_errorbar(aes(ymin=Concentration-sd, ymax=Concentration+sd), size = 1, width = 0, position = position_dodge(width = 0.6)) +
  scale_y_continuous(breaks = c(0,300,600,900,1200,1500,1800,2100,2400,2700,3000)) +
  scale_x_continuous(breaks = c(0,1,2,3,4,5,6,7)) +
  scale_shape_manual(values = c(16,15,17)) +
  scale_color_manual(values=c('#999999','#F5BE6C','#E69F00'))+
  theme_classic() +
  ggtitle("Site 1 - 2019") +
  theme(plot.title = element_text(face = "plain", size = 10, hjust = 0.5)) +
  theme(axis.text.x = element_text(color = "black", size = 10), 
        axis.text.y = element_text(color = "black", size = 10)) +
  theme(axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10)) +
  ylab(bquote("Glyphosate concentration ("*mu~"g/mL)")) +
  theme(legend.position = "none")

# Select data from control and 0.001% GBF-treated hives:
hd1_2019_subset <- hd1_2019[c(1:6,13:18),c(1:4)]

#Line plot with error bars:
hd1_2019_subset_graph <- ggplot(hd1_2019_subset, aes(x=Week, y=Concentration, group=Treatment, color=Treatment)) + 
  geom_line(size = 1, position = position_dodge(width = 0.6), alpha = 0.2, linetype = "dashed") +
  geom_point(size = 4, aes(shape = Treatment, fill = Treatment), position = position_dodge(width = 0.6)) +
  geom_errorbar(aes(ymin=Concentration-sd, ymax=Concentration+sd), size = 1, width = 0, position = position_dodge(width = 0.6)) +
  scale_y_continuous(breaks = c(0,10,20,30,40,50,60,70)) + 
  scale_x_continuous(breaks = c(0,1,2,3,4,5,6,7)) +
  scale_shape_manual(values = c(16,15,15)) +
  scale_color_manual(values=c('#999999','#F5BE6C','#F5BE6C'))+
  theme_classic() +
  ggtitle("Site 1 - 2019") +
  theme(plot.title = element_text(face = "plain", size = 10, hjust = 0.5)) +
  theme(axis.text.x = element_text(color = "black", size = 10), 
        axis.text.y = element_text(color = "black", size = 10)) +
  theme(axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10)) +
  ylab(bquote("Glyphosate concentration ("*mu~"g/mL)")) +
  theme(legend.position = "none")

### Graphs together:
plot_grid(hd1_2019_graph, hd1_2019_subset_graph, labels = "AUTO")
```

# Figure 5D - SITE 2, 2019:
```{r Model}
honey_site2_2019 <- read.table("tables/honey-site2-2019.txt", header = T)

# Function to calculate the mean and the standard deviation for each group
# data: a data frame
# varname: the name of a column containing the variable to be summarized
# groupnames: vector of column names to be used as grouping variables
data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      sd = sd(x[[col]], na.rm=TRUE))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- rename(data_sum, c("mean" = varname))
 return(data_sum)
}

# Summarize the data:
hd2_2019 <- data_summary(honey_site2_2019, varname="Concentration", groupnames=c("Treatment", "Week"))

# Organize:
hd2_2019$Treatment <- factor(hd2_2019$Treatment, levels = c("Control","0_001R_Syrup","0_001R_Water","0_1R_Syrup","0_1R_Water"))

#Line plot with error bars:
hd2_2019_graph <- ggplot(hd2_2019, aes(x=Week, y=Concentration, group=Treatment, color=Treatment)) + 
  geom_line(size = 1, position = position_dodge(width = 0.6), alpha = 0.2, linetype = "dashed") +
  geom_point(size = 4, aes(shape = Treatment, fill = Treatment), position = position_dodge(width = 0.6)) +
  geom_errorbar(aes(ymin=Concentration-sd, ymax=Concentration+sd), size = 1, width = 0, position = position_dodge(width = 0.6)) +
  scale_y_continuous(breaks = c(0,200,400,600,800,1000,1200,1400,1600,1800)) + 
  scale_x_continuous(breaks = c(0,1,2,3,4,5,6,7)) +
  scale_shape_manual(values = c(21,22,23,24,25)) +
  scale_color_manual(values=c('#999999','#F5BE6C','#7FABD3','#E69F00','#3573B9'))+
  scale_fill_manual(values=c('#999999', '#F5BE6C', '#7FABD3', '#E69F00', '#3573B9')) +
  theme_classic() +
  ggtitle("Site 2 - 2019") +
  theme(plot.title = element_text(face = "plain", size = 10, hjust = 0.5)) +
  theme(axis.text.x = element_text(color = "black", size = 10), 
        axis.text.y = element_text(color = "black", size = 10)) +
  theme(axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10)) +
  ylab(bquote("Glyphosate concentration ("*mu~"g/mL)")) +
  theme(legend.position = "none")

# Select data from control and 0.001R-Syrup, 0.001R-Water and 0.1R-Water treated hives:
hd2_2019_subset <- hd2_2019[c(1:12,19:30),c(1:4)]

#Line plot with error bars:
hd2_2019_subset_graph <- ggplot(hd2_2019_subset, aes(x=Week, y=Concentration, group=Treatment, color=Treatment)) + 
  geom_line(size = 1, position = position_dodge(width = 0.6), alpha = 0.2, linetype = "dashed") +
  geom_point(size = 4, aes(shape = Treatment, fill = Treatment), position = position_dodge(width = 0.6)) +
  geom_errorbar(aes(ymin=Concentration-sd, ymax=Concentration+sd), size = 1, width = 0, position = position_dodge(width = 0.6)) +
  scale_y_continuous(breaks = c(0,30,60,90,120,150,180,210,240,270)) + 
  scale_x_continuous(breaks = c(0,1,2,3,4,5,6,7)) +
  scale_shape_manual(values = c(21,22,23,25)) +
  scale_color_manual(values=c('#999999','#F5BE6C','#7FABD3','#3573B9'))+
  scale_fill_manual(values=c('#999999', '#F5BE6C', '#7FABD3', '#3573B9')) +
  theme_classic() +
  ggtitle("Site 2 - 2019") +
  theme(plot.title = element_text(face = "plain", size = 10, hjust = 0.5)) +
  theme(axis.text.x = element_text(color = "black", size = 10), 
        axis.text.y = element_text(color = "black", size = 10)) +
  theme(axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10)) +
  ylab(bquote("Glyphosate concentration ("*mu~"g/mL)")) +
  theme(legend.position = "none")

### Graphs together:
plot_grid(hd2_2019_graph, hd2_2019_subset_graph, labels = "AUTO")
```

# Figure S7 - Checking water consumption at SITE 2
```{r Model}
water_2019 <- read.table("tables/water-control-DW-site2-2019.txt", header = T)

# Subset 1 - Select data from Weeks 0, 0.43, 1, 2:
water_2019_subset1 <- water_2019[c(1:92),c(1:5)]

# Subset 2 - Select data from Weeks 2, 2.43, 3, 4:
water_2019_subset2 <- water_2019[c(93:188),c(1:5)]

# Function to calculate the mean and the standard deviation for each group
# data: a data frame
# varname: the name of a column containing the variable to be summarized
# groupnames: vector of column names to be used as grouping variables
data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      sd = sd(x[[col]], na.rm=TRUE))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- rename(data_sum, c("mean" = varname))
 return(data_sum)
}

# Subset 1:
# Summarize the data:
wd2_2019_1 <- data_summary(water_2019_subset1, varname="Vleft", groupnames=c("Treatment", "Day"))

# Organize:
wd2_2019_1$Treatment <- factor(wd2_2019_1$Treatment, levels = c("Control","0_001R_Syrup","0_001R_Water","0_1R_Syrup","0_1R_Water"))

#Line plot with error bars:
wd2_2019_1_graph <- ggplot(wd2_2019_1, aes(x=Day, y=Vleft, group=Treatment, color=Treatment)) + 
  geom_line(size = 1, position = position_dodge(width = 1.2), alpha = 0.2, linetype = "dashed") +
  geom_point(size = 4, aes(shape = Treatment, fill = Treatment), position = position_dodge(width = 1.2)) +
  geom_errorbar(aes(ymin=Vleft-sd, ymax=Vleft+sd), size = 1, width = 0, position = position_dodge(width = 1.2)) +
  scale_y_continuous(breaks = c(-50,0,50,100,150,200,250,300,350,400,450)) + 
  scale_x_continuous(breaks = c(0,3,7,14)) +
  scale_shape_manual(values = c(21,22,23,24,25)) +
  scale_color_manual(values=c('#999999','#F5BE6C','#7FABD3','#E69F00','#3573B9'))+
  scale_fill_manual(values=c('#999999', '#F5BE6C', '#7FABD3', '#E69F00', '#3573B9')) +
  theme_classic() +
  ggtitle("Site 2 - 2019") +
  theme(plot.title = element_text(face = "plain", size = 10, hjust = 0.5)) +
  theme(axis.text.x = element_text(color = "black", size = 10), 
        axis.text.y = element_text(color = "black", size = 10)) +
  theme(axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10)) +
  ylab(bquote("Water consumption (mL)")) +
  theme(legend.position = "none")

# Subset 2:
# Summarize the data:
wd2_2019_2 <- data_summary(water_2019_subset2, varname="Vleft", groupnames=c("Treatment", "Day"))

# Organize:
wd2_2019_2$Treatment <- factor(wd2_2019_2$Treatment, levels = c("Control","0_001R_Syrup","0_001R_Water","0_1R_Syrup","0_1R_Water","Water"))

#Line plot with error bars:
wd2_2019_2_graph <- ggplot(wd2_2019_2, aes(x=Day, y=Vleft, group=Treatment, color=Treatment)) + 
  geom_line(size = 1, position = position_dodge(width = 1.2), alpha = 0.2, linetype = "dashed") +
  geom_point(size = 4, aes(shape = Treatment, fill = Treatment), position = position_dodge(width = 1.2)) +
  geom_errorbar(aes(ymin=Vleft-sd, ymax=Vleft+sd), size = 1, width = 0, position = position_dodge(width = 1.2)) +
  scale_y_continuous(breaks = c(-50,0,50,100,150,200,250,300,350,400,450)) + 
  scale_x_continuous(breaks = c(14,17,21,28)) +
  scale_shape_manual(values = c(21,22,23,24,25,21)) +
  scale_color_manual(values=c('#999999','#F5BE6C','#7FABD3','#E69F00','#3573B9','red'))+
  scale_fill_manual(values=c('#999999', '#F5BE6C', '#7FABD3', '#E69F00', '#3573B9','red')) +
  theme_classic() +
  ggtitle("Site 2 - 2019") +
  theme(plot.title = element_text(face = "plain", size = 10, hjust = 0.5)) +
  theme(axis.text.x = element_text(color = "black", size = 10), 
        axis.text.y = element_text(color = "black", size = 10)) +
  theme(axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10)) +
  ylab(bquote("Water consumption (mL)")) 
  theme(legend.position = "none")

### Graphs together:
plot_grid(wd2_2019_1_graph, wd2_2019_2_graph, labels = "AUTO")
```
