---
title: "Climate data in Driftwood - years of 2018 and 2019"
author: "Erick Motta"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(cowplot)
```

# Temperature:
```{r Model}
dw_climate <- read.table("tables/climate_data_dw.txt", header = T)

# Organize:
dw_climate$Date <- factor(dw_climate$Date, levels = c("2018-01","2018-02","2018-03","2018-04","2018-05","2018-06","2018-07","2018-08","2018-09","2018-10","2018-11","2018-12","2019-01","2019-02","2019-03","2019-04","2019-05","2019-06","2019-07","2019-08","2019-09","2019-10","2019-11","2019-12"))

#Temperature:
dw_temperature <- ggplot(dw_climate, aes(x=Date, y=Temp_average)) +
  geom_point(size = 2, position = position_dodge(width = 0.2)) +
  geom_errorbar(aes(ymin=Temp_min, ymax=Temp_max), size = 0.5, width = 0, position = position_dodge(width = 0.2)) +
  theme_classic() +
  scale_y_continuous(breaks = c(0,5,10,15,20,25,30,35,40)) +
  ggtitle("Temperature in Driftwood, TX (2018-2019)") +
  theme(plot.title = element_text(face = "plain", size = 10, hjust = 0.5)) +
  theme(axis.text.x = element_text(color = "black", size = 8, angle = 45, vjust = 0.6),
        axis.text.y = element_text(color = "black", size = 10)) +
  theme(axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10)) +
  ylab(bquote("Temperature (oC)")) +
  theme(legend.position = "none")

#Precipitation:
dw_precipitation <- ggplot(dw_climate, aes(x=Date, y=Precipitation)) +
  geom_point(size = 2, position = position_dodge(width = 0.2)) +
  theme_classic() +
  scale_y_continuous(breaks = c(0,25,50,75,100,125,150,175,200,225,250,275,300)) +
  ggtitle("Rainfall in Driftwood, TX (2018-2019)") +
  theme(plot.title = element_text(face = "plain", size = 10, hjust = 0.5)) +
  theme(axis.text.x = element_text(color = "black", size = 8, angle = 45, vjust = 0.6),
        axis.text.y = element_text(color = "black", size = 10)) +
  theme(axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10)) +
  ylab(bquote("Rainfall (mm)")) +
  theme(legend.position = "none")

### Plotting data:
plot_grid(dw_temperature, dw_precipitation, labels = "AUTO")
```
